### ISSUE TITLE
New resource

### ISSUE THREAD

**Issue by lawsie** [raspberrypilearning/the-all-seeing-pi#1]
Another new one @SteveAmor (this is currently in for copy edit but as it's quite a complicated one there are probably bugs!)

**Comment by SteveAmor** [comment]
Working through them with a beginner.  Can you upload the other overlays you have @lawsie ?

**Comment by SteveAmor** [comment]
Possibly, 'blackhat', 'emo2', 'baseball', 'santa', 'alps'
blackhat may now be top.png?
I'm assuming santa is the big white beard :-)

**Comment by lawsie** [comment]
Oh yeah! Weird. I must have had a different set of overlays on the pi to on my work computer. I'll have a look (but I need to be a bit careful as sometimes the overlays don't work if they get saved somehow in an odd format). All the PR's have either been merged or sent for copy editing, thanks very much.

**Comment by lawsie** [comment]
There you go - the other overlays are now added.
