### ISSUE TITLE
'next_overlay' is not defined

### ISSUE THREAD

**Issue by oichapman** [raspberrypilearning/the-all-seeing-pi#29]
Hi, thought i'd give this project a go as it looks like fun. 

I've got a brand new pi and followed the instructions carefully however i'm falling over when trying to test the buttons. 

The error i'm getting is 

`Traceback (most recent call last):
File "/home/pi/allseeingpi.py", line 4, in <module>
next_overlay_btn.when_pressed = next_overlay
NameError: name 'next_overlay' is not defined`

Any ideas on what i'm doing wrong please?

**Comment by MarcScott** [comment]
Have you followed all the steps on https://projects.raspberrypi.org/en/projects/the-all-seeing-pi/11
You need to have all the files here - https://github.com/raspberrypilearning/the-all-seeing-pi/tree/master/en/resources in the same directory as your main code.

Then when you add `from overlay_functions import *` to the top of your code, the `next_overlay` function should be available for you to use.

**Comment by oichapman** [comment]
Thank you - yes this resolved the issue.
